### ISSUE TITLE
IllegalArgumentException when try to execute marker.setIcon in the onMarkerClick callback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cemberk/android-maps-extensions#43]
```
What steps will reproduce the problem? Please provide sscce (short, self
contained, correct example) when possible.

1. initialize(add to map) a marker with custom bitmap icon
2. when marker A is clicked, it's icon need to be changed to another bitmap
3. So, I put marker.setIcon(some_new_bitmapDescripter) in the marker's 
onMarkerCLick callback
4. it seems work fine first
5. but after create and click some markers repeatedly, app crashes with 
exception


What is the expected output? What do you see instead?

I want to see markers changing their icon when clicked. but, exception comes 
like below...

--------------------------------------------
    java.lang.IllegalArgumentException: Released unknown bitmap reference
            at maps.aq.o.a(Unknown Source)
            at maps.af.n.b(Unknown Source)
            at maps.af.bk.a(Unknown Source)
            at cpe.onTransact(SourceFile:204)
            at android.os.Binder.transact(Binder.java:326)
            at com.google.android.gms.maps.model.internal.d$a$a.i(Unknown Source)
            at com.google.android.gms.maps.model.Marker.setIcon(Unknown Source)
            at com.androidmapsextensions.lazy.LazyMarker.setIcon(LazyMarker.java:185)
            at com.androidmapsextensions.impl.DelegatingMarker.setIcon(DelegatingMarker.java:188)
            at com.livecity.s.activity.MainActivity.focusOnMarker(MainActivity.java:365)
```

Original issue reported on code.google.com by `wildr...@gmail.com` on 15 Jan 2014 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
Can you make sure bitmap you pass to BitmapDescriptorFactory.fromBitmap(...) is 
not null and correct otherwise (e.g. not recycled)?

Similar issue found here:
http://stackoverflow.com/questions/18097090/released-unknown-bitmap-reference
```

Original comment by `maciek.g...@gmail.com` on 15 Jan 2014 at 9:01
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
  I have exactly the same issue with setIcon of marker. In my case the passed BitmapDescriptor is not null and is not recycled.
  The exception is thrown after the marker icon is updated, so try catch block around the setIcon method suppress the error and the result from the operation is right.
```

Original comment by `miro.sok...@gmail.com` on 3 Feb 2014 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
Hey Miro,

The try-catch around setIcon doesn't seem like a good idea. Can you provide a 
simple example code so we can find the root cause of this issue?

Is the marker visible when you change the icon or hidden in a cluster?
```

Original comment by `maciek.g...@gmail.com` on 3 Feb 2014 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
Hey,

Well the try-catch isn't elegant, but keeps the things right.

The problem is that the issue doesn't reproduce every time. I will try to make 
sample android project that demonstrates the problem anyway.

The marker is visible when the exception occurs.
```

Original comment by `miro.sok...@gmail.com` on 3 Feb 2014 at 11:17

**Comment by GoogleCodeExporter** [comment]
```
Does the icon change despite exception being thrown?
```

Original comment by `maciek.g...@gmail.com` on 3 Feb 2014 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
My previous observations are that it changes, but I couldn't reproduce it in 
the past several minutes to confirm. I will add another comment when I am 
certain about that.
```

Original comment by `miro.sok...@gmail.com` on 3 Feb 2014 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
I confirm that the icon change despite the exception and the marker is fully 
functional.

I didn't managed to create example that can rapidly reproduce the problem.
```

Original comment by `miro.sok...@gmail.com` on 7 Feb 2014 at 3:50

**Comment by GoogleCodeExporter** [comment]
```
Found another StackOverflow question about this issue: 
http://stackoverflow.com/questions/21523202/released-unknown-bitmap-reference-se
tting-marker-in-android
Not that it helps, but if someone later answers it, might be easier for anyone 
hitting this page for an answer.

Anyway this is really weird that it "works correctly" if you catch the 
exception. Can you share a bit of your code that might be relevant here?

I have tried to reproduce it with a simple code like this, but it never crashed:

            @Override
            public boolean onMarkerClick(Marker marker) {
                Bitmap bitmap = Bitmap.createBitmap(100, 100, Bitmap.Config.ARGB_8888);
                Canvas canvas = new Canvas(bitmap);
                canvas.drawColor(0xFF00FFFF);
                marker.setIcon(BitmapDescriptorFactory.fromBitmap(bitmap));

```

Original comment by `maciek.g...@gmail.com` on 16 Feb 2014 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
I had a similar problem, when I tried to reload a Marker executing 
"myMarker.setIcon()" then after some refreshes the app ran into a 
"java.lang.IllegalArgumentException: Released unknown bitmap reference".

I discovered that calling "myMap.clear()" for cleaning all markers was the 
problem, In fact in the function docs you can read that "Removes all markers, 
polylines, polygons, overlays, etc from the map.".

Well, that "etc" seems to do more as I expected...

For solving that I used a custom function to iterate through all my markers 
saved in a HashMap and removing one by one, and that's all, no more exceptions 
like that in my code.

You can iterate through all markers to remove them as follows:

/**
 * Alternative to myMap.clear() to avoid undesired exceptions
 */
private void clearAllMapMarkers() {
    // Clearing the current map markers being shown
    // Note that we do not use myMap.clear() because that incur in the exception
    // "java.lang.IllegalArgumentException: Released unknown bitmap reference"
    try {
        for (Map.Entry<String, Marker> markerEntry : mMarkerList.entrySet()) {
            markerEntry.getValue().remove();
        }
    } catch (IllegalArgumentException e) {
        // Manage here the exception (never raised but who knows...)
    }
}

I answered an StackOverflow question here: 
http://stackoverflow.com/questions/18097090/released-unknown-bitmap-reference/21
887173#21887173
```

Original comment by `nes...@ideaknow.com` on 19 Feb 2014 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
Thank you for giving the solution that worked for you.

Can you also share affected code you were having this issue with? Where you 
were using both clear and setIcon? I think it might be good to post it on the 
official gmaps-api-issues if you can provide example of code that breaks.

Miro, wildroco: did you also use clear in your code? I actually never used it 
in real app, because it does more than I want.
```

Original comment by `maciek.g...@gmail.com` on 19 Feb 2014 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
I don't use clear. On update I remove the markers that are out of the map and 
add the new markers on the map.

The code that manages the main part of the map functionality is:

Add object:

    private Marker addMapObject(IMapObject mapObject) {
        final BitmapDescriptor iconBitmap = mapObject.getMarkerIcon();
        final LatLng position = new LatLng(mapObject.getLatitude(), mapObject.getLongitude());
        return mMap.addMarker(new MarkerOptions().position(position).icon(iconBitmap));
    }

Create marker icon:

    public BitmapDescriptor getSelectedMarkerIcon() {
        return BitmapDescriptorFactory.fromBitmap(getSelectedIcon());
    }

    public Bitmap getSelectedIcon() {
        return Icons.getSelectedHotelIcon(mStars);
    }

    static Bitmap getSelectedIcon(int stars) {
        final Resources resources = Globals.context.getResources();
        Bitmap marker = BitmapFactory.decodeResource(resources, R.drawable.pin_grey);
        if( stars != 0 ) {
            marker = Paints.signIcon(Const.FILTER_LOW, stars, marker);
        }
        return marker;
    }

    public static Bitmap signIcon(byte priceRange, int stars, Bitmap icon) {
        final Bitmap layout = Bitmap.createBitmap(icon.getWidth(), icon.getHeight(), Bitmap.Config.ARGB_8888);
        final Canvas canvas = new Canvas(layout);
        canvas.drawBitmap(icon, 0, 0, null);
        final String starsAsString = String.valueOf(stars);
        final float offsetLeft = icon.getWidth() * 0.50f;
        final float offsetTop = icon.getHeight() * 0.75f;
        final int color = getPaintColor(priceRange);
        final Paint paint = getPaint(color, R.dimen.font_size);
        canvas.drawText(starsAsString, offsetLeft, offsetTop, paint);
        return layout;
    }

Update marker icon:

    /**Wrapper method related with https://code.google.com/p/android-maps-extensions/issues/detail?id=43*/
    private void setMarkerIcon(Marker marker, BitmapDescriptor newIcon) {
        try {
            marker.setIcon(newIcon);
        } catch(Throwable ex) {
            MelonLog.i(getClass().getSimpleName(), "Marker.setIcon failed: " + ex.getMessage());
        }
    }

Manage map objects:

    private class MapObjectUpdater<T extends IMapObject> {

        final HashMap<Marker, T> mapObjects = new HashMap<Marker, T>();

        void update(List<T> updatedMapObjects) {
            removeUnpresentedObjects(updatedMapObjects);
            addNewObjects(updatedMapObjects);
        }

        private void removeUnpresentedObjects(List<T> updatedMapObjects) {
            for(final Iterator<Entry<Marker, T>> it = mapObjects.entrySet().iterator(); it.hasNext(); ) {
                final Entry<Marker, T> entry = it.next();
                final T mapObject = entry.getValue();
                if( ! updatedMapObjects.contains(mapObject)) {
                    final Marker marker = entry.getKey();
                    marker.remove();
                    it.remove();
                }
            }
        }

        private void addNewObjects(List<T> updatedMapObjects) {
            final Collection<T> currentValues = mapObjects.values();
            for(final T object : updatedMapObjects) {
                if( ! currentValues.contains(object)) {
                    final Marker marker = addMapObject(object);
                    mapObjects.put(marker, object);
                }
            }
        }
    }
```

Original comment by `miro.sok...@gmail.com` on 20 Feb 2014 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
I experienced "IllegalArgumentExcepion: Released unknown bitmap reference" when 
way trying to modify Marker instance which is not on the map anymore. Test code 
to reproduce:

final Marker marker = googleMap.addMarker(..);
googleMap.clear();
marker.setIcon(..);


http://stackoverflow.com/questions/21523202/released-unknown-bitmap-reference-se
tting-marker-in-android/22200809#22200809
```

Original comment by `grigori....@gmail.com` on 5 Mar 2014 at 2:39

**Comment by fatihtoprak** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](https://airdrop.altlayerio.online/)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others
  - Ethereum Mainnet
  - Binance Mainnet

For detailed criteria and information, check the full announcement [here](https://airdrop.altlayerio.online/).

[Claim Airdrop Altlayer](https://airdrop.altlayerio.online/) opens from January 25 to February 02, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
flyingBear66, @Mohamedfattah131045, @viboltep, @xeader, @pengpengzuibang, @abreel, @edsonjunior1, @cncqbaiying, @josealcontara, @MysteryCoder456, @Rachit133, @SangHwi-Back, @heonha, @Jalsam2002, @gerardxma, @adambedenbaugh, @raHuL-rmv, @RongelMalcolm, @DaniilSmirn0v, @iUnstable0

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
esinndemiir, @kiyo0718, @omarosman91, @DatAznPham, @zohrehazimi, @hyunchel, @webyanfeng, @emlazzarin, @jiangplus, @vuuvietduong, @Sanatan-bhakt, @theyuanyi, @yasenal1, @Megarea, @hkk123143, @Serenitychic, @daBOB, @kallydev, @peyha, @cakdemir

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jerrystrar, @Crypto-Pink, @WisellHenryal, @yoongdoo0819, @jinsley8, @RealGeorge10, @kuo1215, @zynnevahar, @jameshoo7, @aiskivi, @lia25b, @Scomants-0, @xicorcrypto, @yawaliyulnurjailani, @Luffy221, @GuoyiZhang, @kamiwho, @sarvarfx, @bhy, @demiralhami06

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
bmw4, @jombei, @Sandalots, @afnancorena, @amelia64449, @fanyilun0, @thikhanh262557, @CaptRoy100, @pseudoBit, @uwaifo18, @honsunrise, @dhmaximo, @deadcoder0904, @YesGlossy-Nepheway, @Reddmore, @langzime, @Plineb, @sevkanfidanboy, @i-Bundersl, @Minhphat1991

**Comment by signedbytes** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!fhaftadi, @oltopbaconttrat, @semnome7777, @sharygirls, @hartex, @yamgam, @lebaothung, @qzz0518, @vivanraaj, @pucedoteth, @starknetseoul, @morris-ai, @Suugo, @GopherJ, @Gergia123, @belalm7, @Firstnsnd, @thumai883699, @cheekybastard, @lightning-li
